# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Rounding Technical Pegs'
tagline:          'The boring side of the cutting edge'
description:      'The boring side of the cutting edge'
url:              http://blog.roundingpegs.com
baseurl:          /

author:
  name:           'Brian Marick'
  url:            https://twitter.com/marick

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/roundingpegs
